version: '3'
services:
    conda:
        build: .
        ports:
            - "8888:8888"
            - "6006:6006"
        volumes:
            - ../pyimagesearch:/opt/pyimagesearch
        working_dir: /opt/pyimagesearch
        environment:
            - DISPLAY=host.docker.internal:0
        command: /bin/bash -c "/opt/conda/bin/jupyter lab --ip='0.0.0.0' --port=8888 --no-browser --allow-root"